### ISSUE TITLE
[Feature Request] Default name while saving a image/pane

### ISSUE THREAD

**Issue by skrish13** [facebookresearch/visdom#136]
Can we have the default plot name while saving a plot/pane/window as either the pane-id or title of the plot or label? Anything which is related to that pane than just "newplot.png" (currently).

Thanks :)

**Comment by lvdmaaten** [comment]
I don't see why not. Please feel free to send a PR!

**Comment by skrish13** [comment]
Any pointers as to how to do it?

**Comment by lvdmaaten** [comment]
Hmmm... the `newplot` name seems to come from here: https://github.com/plotly/plotly.js/blob/43d3710bdb183f9c1681f40efe8649a7238efce5/src/snapshot/download.js#L49

I'm not quite sure if that's what you mean though? The name we specify already appears to be the name of the pane: https://github.com/facebookresearch/visdom/blob/master/js/PlotPane.js#L48

**Comment by skrish13** [comment]
Riiight.... Just to clarify, I mean the filename which comes when you use "download plot as png" option.

**Comment by lvdmaaten** [comment]
That button is implemented in Plotly, not in visdom: https://github.com/plotly/plotly.js/blob/5da37913cb2d52ed3ad9b161b66f361a142ca1e1/src/components/modebar/buttons.js#L48,L70

You would have to submit a PR in that repo, adding a `filename` option here: https://github.com/plotly/plotly.js/blob/5da37913cb2d52ed3ad9b161b66f361a142ca1e1/src/components/modebar/buttons.js#L62

I will close this issue, because this is not a visdom feature / issue.

**Comment by skrish13** [comment]
Ahh, okay! Thanks :)
