### ISSUE TITLE
Visdom cannot plot small numbers?

### ISSUE THREAD

**Issue by HenryZhou7** [facebookresearch/visdom#152]
I was using viz.line() tool to plot learning curves. When I am trying to overfit on a small dataset, the loss quickly converges to 0 from around 1. But visdom seem not to plot very small numbers. I am talking about something in 1e-6 or 1e-9 in magnitude. 

Is this a normal issue?

**Comment by lvdmaaten** [comment]
What do you mean by "visdom [does] not ... plot very small numbers"? It rounds them to zero?

I presume this is related to what happens to numbers when they're serialized by `json.dumps`: https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L240
There are several topics about how to change the rounding behavior of this function on StackOverflow, but most of them seem to involve getting less precision rather than more precision in the serialized numbers...
