### ISSUE TITLE
How to install visdom on a linux server which can't reach the internet?

### ISSUE THREAD

**Issue by shouguicai** [facebookresearch/visdom#161]
I have just upload the package download by own computer and upload it to the server,
cd to the path of visdom and try python setup.py install.

![11](https://user-images.githubusercontent.com/5772802/31017916-bde7aeca-a55c-11e7-9e44-489374d34f1e.PNG)
when i run python -m visdom.server, it does't print 'It's Alive' and i can't reach it by my chrome.
![22](https://user-images.githubusercontent.com/5772802/31017968-f9c99692-a55c-11e7-9ce2-fda092e3034e.PNG)
may someone help me with this, thanks.

**Comment by lvdmaaten** [comment]
The dependencies on external libraries at run-time were fixed by https://github.com/facebookresearch/visdom/commit/b5bca2ec536ca64af933019b25720ed935025fcb. Have a look at the `download_scripts()` function in that commit. If your server cannot access the internet, you basically want to download the packages listed there manually, and `scp` / `rsync` them into the location described in the function. If the files already exist, the server will not try to re-download them.

**Comment by shouguicai** [comment]
Thanks for your reminder. Problem solved.
