### ISSUE TITLE
If client is behind a firewall, which port should I forward?

### ISSUE THREAD

**Issue by teracamo** [facebookresearch/visdom#176]
I am currently hosting the server over a DMZ IP, but when ever my client is behind a router, the server will display offline after loading the site. I figure it might be listening to updates, but the port is not fowarded

**Comment by JackUrb** [comment]
If clicking the `offline` button to try and toggle it to online doesn't successfully work, I'd suggest trying to forward the port that the visdom server is communicating on (`8097` by default).

**Comment by teracamo** [comment]
The offline button remains red after clicking. And I tried forwarding 80, 8097, 8080, 8000, they all dosen't seemed to work

**Comment by teracamo** [comment]
I further tested and it seems that only clients within the same intranet can gain access to the server through a post request issued by main.js where the only param is "sid". If client is not within the intranet, it wouldn't give out this post request.

**Comment by JackUrb** [comment]
The issue is coming before the sid post request. If the button never turns green, the [socket](https://github.com/facebookresearch/visdom/blob/master/js/main.js#L149) is never being opened. Are there any errors in your js console when clicking the button?

**Comment by teracamo** [comment]
I can see the "socket" request is published, but the response is empty. Also there were no javascript error, only some warning: 
```
Source map error: request failed with status 404
Resource URL: https://unpkg.com/layout-bin-packer@1.2.2
Source Map URL: layout-bin-packer.js.ma
```
![untitled](https://user-images.githubusercontent.com/11690091/31753872-1f0b1fd4-b4c6-11e7-8947-c0570e10cb7f.png)

I also suspect if root privilege is required to host the server?

**Comment by lvdmaaten** [comment]
Are you sure you are on the latest version of visdom? 

We recently changed the behavior of visdom: rather than having the JavaScript code rely on external JS scripts that may sometimes be unavailable, we now switched to a model in which the server downloads all external JS scripts at launch time and serves them to the client. Users may still suffer from 404 errors in the new setup, but then the 404 error should show up at server launch time rather than on the client-side. Do you see this error at server launch time: https://github.com/facebookresearch/visdom/blob/master/py/server.py#L617 ?

If you are on the latest version of visdom, perhaps you have to set the `proxies` variable here: https://github.com/facebookresearch/visdom/blob/master/py/server.py#L634

(Note to self: we should expose the `proxies` argument via the input arguments of the server.)

**Comment by teracamo** [comment]
Actually I have two machines testing on the same matter, one is an intranet server with updated visdom but no control to firewall rules of client-server traffic, another is an internet server with ```pip install visdom`` version, but I have full control of the firewall. Both showed the same symptoms. I will try to update the internet server first.

About that proxies, would there be any documents on how to configure that? What should I set to the proxies variable?

Thanks man!

**Comment by JackUrb** [comment]
You can see what to provide proxies [here](https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyHandler). Examples can be found by finding examples of the ProxyHandler class, but the general idea is it takes a dict that maps connection protocols ('http', 'https', etc.) to proxy ip addresses.

**Comment by teracamo** [comment]
The proxy trick eventually worked. Turns out the two machines I tested had two different problems with the same symptoms. 

One is because the firewall allow traffic by applications instead of by port, and hence visdom server is not allowed since it is not on their list (which I am not sure how they differentiate visdom requests from other http requests, maybe they are checking the headers). 

Another is because of the out dated version and incorrect proxy settings
