### ISSUE TITLE
Feature request: is it possible to disable the background grid when plotting?

### ISSUE THREAD

**Issue by HenryZhou7** [facebookresearch/visdom#200]
[sample.pdf](https://github.com/facebookresearch/visdom/files/1464398/sample.pdf)

I am wondering if it is possible to remove the grid from the final plot. Is there an option? Thanks!
There is an example cropped PDF attached.

**Comment by JackUrb** [comment]
This, like https://github.com/facebookresearch/visdom/issues/197, is a feature supported by [plotly](https://github.com/facebookresearch/visdom/issues/175) but that we only expose through our [generic plotting](https://github.com/facebookresearch/visdom#generic-plots) method. It can be fixed by adding `'showgrid'` to the list altered in https://github.com/facebookresearch/visdom/pull/191, however long term it would be best to allow packaging of arbitrary layout in the `_opts2layout` method
