### ISSUE TITLE
[Feature Request] Any way to draw different color in a line?

### ISSUE THREAD

**Issue by theFool32** [facebookresearch/visdom#208]
![image](https://user-images.githubusercontent.com/3063690/33177818-f40a0468-d09e-11e7-8ee3-1a6f93c15bcc.png)
For example, like the picture shows. It's useful when training with udpating different paramaters.
I don't know whether it can be done with current api. If it is possible, how to achieve it?

Thanks a lot.

**Comment by lvdmaaten** [comment]
As far as I can tell, plot.ly currently does not support this type of plot. There is an open issue about it [here](https://github.com/plotly/plotly.js/issues/147).

I'm closing this issue here, because it is a feature that needs to be added to plot.ly (rather than to visdom). Please let me know if you have any further questions.
