### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by Seraphli** [facebookresearch/visdom#222]
FYI, getting `Connection refused` error or any timeout error in China while starting the server using `python -m visdom.server` is caused by GFW. You can see the console doesn't output any information, which means the script is stuck on downloading required js and css. So I fork this repository and download all required scripts. If someone is having this problem, please check out [my fork](https://github.com/Seraphli/visdom/tree/pre-download).
BTW, I don't whether it's good or not to create a pull request about this issue. So I haven't created a pull request yet.

**Comment by lvdmaaten** [comment]
We are not allowed to re-distribute code by third parties (even if the code license allows it), which is why we download the dependencies at server launch time. For that same reason, we will not be able to accept your pull request.

Having said that, folks in China with firewall issues are presumably greatly helped by your fork. Thanks for setting it up!

We are thinking about a more permanent solution to the problem. Suggestions are welcome!

**Comment by Seraphli** [comment]
I manage to solve this problem, and I create a pull request #224 . I will keep the `pre-download` branch in my fork in case someone needs it.

**Comment by lvdmaaten** [comment]
Awesome, thank you! 

We are importing your PR. Closing this issue as I presume it is solved.
