### ISSUE TITLE
'URLError' object has no attribute 'code'

### ISSUE THREAD

**Issue by SherilynW** [facebookresearch/visdom#240]
```
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/visdom/server.py", line 717, in <module>
    download_scripts()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/visdom/server.py", line 697, in download_scripts
    logging.error('Error {} while downloading {}'.format(exc.code, key))
AttributeError: 'URLError' object has no attribute 'code'
```
I got these when I was starting the server.
It seems that I have something wrong with the port......

**Comment by JackUrb** [comment]
Hi @SherilynW - are you running from the pip version or have you built from source? 

If from source, can you change that format call to read `.format(exc.reason, key)` instead and paste the reason?

**Comment by SherilynW** [comment]
I am running from the pip version. I have adjusted the scrip, but later found these issues:
```
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) 
while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-
regular.svg#glyphicons_halflingsregular
```

**Comment by lvdmaaten** [comment]
That URL downloads fine for me, so I'm unsure why you're unable to verify the SSL certificate. Perhaps this is some firewall or VPN-related issue?

Your best option is probably to try and do a manual install of the dependencies as described in `CONTRIBUTING.md`. Alternatively, you could try to bypass the SSL certification by adding the following at the top of `py/server.py` before start the server:
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
Note that this is *very dangerous*, so immediately remove this monkey-patch after the server started successfully the first time, and restart the server. (The server only downloads the dependencies the first time you start it.)

I'm closing the issue because https://github.com/facebookresearch/visdom/pull/242 fixed the issue in the error logging. Thanks for reporting!

**Comment by SherilynW** [comment]
Thanks, this works for me :)
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
