### ISSUE TITLE
Feature request: _send raises exception instead of printing it

### ISSUE THREAD

**Issue by varunagrawal** [facebookresearch/visdom#241]
In the `Visdom` class's `_send` method, if the post request raises an exception, the exception handler prints the exception and returns false instead of raising it.

It would be nice if the exception handler raised the exception and let the user handle it based on the use case. The exception raised could have useful contextual information instead of printing out the exception, as printing the exception may pollute loggers set up for the code.

**Comment by varunagrawal** [comment]
I can work on this and submit a PR if needed.

**Comment by JackUrb** [comment]
@varunagrawal While generally I agree this would be useful, it's important to note that for people who already have visdom in their workflow this could break an experiment if anything happens. This behavior is also already depended on by some functions, such as `win_exists`.

If you want to implement this feature, I'd suggest making it an option that is put into the `__init__` method of the Visdom class and defaults to False, and then update `win_exists` to be able to handle either case. 

You can even include a deprecation warning message for those starting with the default value that 'Visdom is eventually changing to default to raising rather than ignoring' and telling them to start supplying the value by having it default to None and then if it is None send the warning and then set to false.

Other than that tidbit I'd be happy to accept this.

**Comment by varunagrawal** [comment]
@JackUrb Would it be better to deprecate this functionality in favor of the new one? For the time being, I can implement it as you have requested, but it would be great to perhaps add a deprecation warning or rewrite this while notifying folks of the breaking change. 

I am not sure if Visdom follows any particular release cycle or is it released on a rolling basis.

**Comment by JackUrb** [comment]
I think it would indeed be better to deprecate the supressed-by-default behavior that visdom currently has for errors. If you put a date in it a few months from now I feel that would be enough warning.

As of now we don't follow a particular release cycle - I tend to move things from the Github to pypi every other week or so once I'm sure it doesn't break anything.

**Comment by varunagrawal** [comment]
Your argument on experiment workflow makes a lot of sense and I completely agree with it.

Here's an alternative to raising the exception: we allow a flag to suppress warning being printed out. This way Visdom behaves more like a logger while fixing the previous issue I raised as well.

As for which exceptions should be suppressed vs which should be handled by the user, I guess that is an intensive discussion on its own. I'd be happy to collaborate on that.

If you think the idea for a warning suppression flag is the right thing to do, I'll go ahead and update the issue and you can assign it to me.

**Comment by JackUrb** [comment]
I think having that kind of flag is mostly where my suggestion in https://github.com/facebookresearch/visdom/issues/241#issuecomment-355655626 referred to. Users could then use the flag to either have warnings/exceptions printed or to have them raised so they can be handled appropriately. 

I'd be happy to have that kind of functionality.

**Comment by JackUrb** [comment]
Hi @varunagrawal - Have you had a chance to take a look at this?

**Comment by varunagrawal** [comment]
Hi @JackUrb I'm almost done working on it. Will raise a PR by tomorrow latest.
