### ISSUE TITLE
Viz line update does not work

### ISSUE THREAD

**Issue by zzzace2000** [facebookresearch/visdom#244]
I try to update the viz line and it does not work.

Here is the minimal example:
```
import visdom
import numpy as np

viz = visdom.Visdom()
win = viz.line(
    X=(np.arange(0, 10)),
    Y=(np.linspace(5, 10, 10)),
)
```
Then I update the window with replace.
```
viz.line(
    X=(np.arange(0, 10)),
    Y=(np.linspace(5, 10, 10)) - 10,
    win=win,
    update='replace'
)
```
It does not work. Can you let me know what I might go wrong?

**Comment by lvdmaaten** [comment]
This issue was fixed in https://github.com/facebookresearch/visdom/pull/234/files. Your example works fine for me using the latest version of the code.

We will update the pip install shortly to include this fix. In the meantime, you can do an install from source (see `CONTRIBUTING.md` for details).
