### ISSUE TITLE
Error when loading svg image TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by jj0mst** [facebookresearch/visdom#252]
This happens when i try loading an svg image using Visdom.svg().
I think i fixed it in my case replacing the following line from [https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L370](url):
`svgstr = loadfile(svgfile)`
with
`svgstr = str(loadfile(svgfile))`
but i don't know if it works in every case.

**Comment by JackUrb** [comment]
I'm fairly certain we've only rigorously tested locally generated svgs (thus already strings) rather than the file loaded ones. Considering we expect that value to be a string rather than a bytes-like object, forcing a string conversion is definitely safer than what we have. I'd be happy to accept your fix if you want to open a PR for it 👍

**Comment by jj0mst** [comment]
The problem is [here](https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L71).

When the svg() method is given an svgfile it uses the loadfile() method, but this one reads the file in 'rb'.

We could change it to choose the reading mode (bytes or string), but i think it's easier to just convert it after reading.

Here is the PR: #253
