### ISSUE TITLE
[Feature Request] Add 'readonly' flag to visdom.server

### ISSUE THREAD

**Issue by dizcza** [facebookresearch/visdom#256]
How can I share my work with other people such that they could only _view_ the plots? It'd be nice to have the ability to block any changes made by a user to the server.

**Comment by JackUrb** [comment]
Your best bet is to look into how the server handles incoming requests from the frontend. Everything comes in through the `SocketHandler` class. You could potentially add a flag that makes modifying calls to `on_message` no-ops, and then update the `main.js` file such that the online indicator had a third option (read-only?) which would disable the buttons in the same way that `state.connected` is used to enable/disable those buttons. You would also need a way to broadcast the fact that it's a read-only state to the frontend, which is handled through the socket in `_handleMessage` in `main.js`.

**Comment by xssChauhan** [comment]
Hello @JackUrb, I would like to take up this issue.
I was looking at the source and the incoming commands on `SocketHandler.on_message` that need to filtered for readonly flag would be: `close`, `delete_env`, `save_layouts`. 

Am i correct in grasping this?

**Comment by JackUrb** [comment]
@xssChauhan Yup that's correct! Nothing else would necessarily need to change for a read-only mode

**Comment by xssChauhan** [comment]
@JackUrb Thank you! I am currently thinking of setting a global variable/environment variable to indicate the read-only state if an argument is passed from the cli. And returning early in the `on_message` method when the read-only state is set and the `cmd` is one of the actions that needs to be blocked.

**Comment by JackUrb** [comment]
Seems like a perfectly valid approach to me.

As an extension, if you're interested it'd be appreciated if you also send that as a parameter in the `open` function of the `SocketHandler`, this way the frontend could render "read-only" rather than just "online" in the top right corner.

Currently register only sends the socket id, but this would be where you could also send the read-only status: https://github.com/facebookresearch/visdom/blob/8779e3862412edc99176f4d17e20a2ba61f6280a/py/visdom/server.py#L233

And then if you're really interested you can then use that in the JS client by making read-only a part of the react state, and changing this text based on that state: https://github.com/facebookresearch/visdom/blob/8779e3862412edc99176f4d17e20a2ba61f6280a/js/main.js#L1071

**Comment by xssChauhan** [comment]
My aim is to provide a complete solution to the issue.
I'll definitely take care of the rest of the implementation as well.
Thank you for the references.
