### ISSUE TITLE
Question about Licensing

### ISSUE THREAD

**Issue by esc** [facebookresearch/visdom#257]
I was wondering if you could clarify, why you chose to license the Project using a Creative Commons licences? I'd also be interested what implications this has from a legal standpoint.

**Comment by lvdmaaten** [comment]
Thanks for your question.  We chose CC-NC-4.0 here because it is a Creative Commons license (which is well-known within the open source community) and we would prefer the code to be able to be used by researchers but not for commercial purposes.  Unfortunately, we cannot provide legal advice for you in this forum, but you should read the explanation by Creative Commons of their licenses here: https://creativecommons.org/licenses/.  If you feel like you need more advice you should seek advice of an attorney.
