### ISSUE TITLE
Supporting script tags in TextPanes

### ISSUE THREAD

**Issue by OlegJakushkin** [facebookresearch/visdom#258]
arbitrary HTML added via `vis.text`:

```
<script type='text/javascript' src='http://www.x3dom.org/download/x3dom.js'> </script>  <link rel='stylesheet' type='text/css' href='http://www.x3dom.org/download/x3dom.css'></link><div style='height: 200px;width: 100%;' id='1'  width='100%' height='200px'><x3d style='height: 200px;width: 100%;' id='1' width='100%' height='200px'><scene><shape><appearance><material diffuseColor='0.603 0.894 0.909'></material></appearance> <box></box></shape></scene></x3d></div>
```

Had to create something like this:
![image](https://user-images.githubusercontent.com/2915361/35782251-5843c658-0a06-11e8-957e-401126b52764.png)

Yet greated this:
![image](https://user-images.githubusercontent.com/2915361/35782256-685bf93e-0a06-11e8-9bc9-6e5f06b25b32.png)

As you can see - no X3D element is present due to the absence of `link` and `script` tags. Please add an option to start server allowing such text input.

**Comment by JackUrb** [comment]
Text panes allow arbitrary javascript by doing direct setting of the inner HTML:
https://github.com/facebookresearch/visdom/blob/590c790562a938442c48e69a5f8dec821ae75fc4/js/TextPane.js#L27

To my knowledge this method does not allow for script injection. I don't know of any good methods that do allow script injection. If you or anyone else comes up with an implementation that works however I'd be happy to accept it.

**Comment by lvdmaaten** [comment]
I'm wondering if adding a function such as this one would do the trick: http://www.javascriptkit.com/javatutors/loadjavascriptcss.shtml

Rather than adding the `script` and `link` tag, you could then call something akin to the `loadjscssfile()` function to load external JS and CSS files to make the above example work.

**Comment by JackUrb** [comment]
@lvdmaaten though in that solution it would be required that the text pane figure out how to parse the given html for script and link components automatically. Creating a text pane doesn't really expose a method for calling functions on the frontend client to my knowledge

**Comment by OlegJakushkin** [comment]
Ended up using old-bad **`iframes`** (with flask, bootstrap and x3d inside), so it is a closed issue for me. 

The main drawback is that browsers are still challenged with iframe+BlaGL dragging around (mouse faster than view movement leads to window movement freeze, hard on GPU - seen some browser tab crushing).

Notes: it would be nice to have more control over windows\NavBar:
1.	download arrow is useless when content is a html text about `iframe` I would love to have an option to turn it off
2.	cross is painful when you want to create a window that creates other windows
3.	related to 2. – ability to expand navbar instead of checking if `win_exists` once a second due to `clear` button cleansing all windows would be so nice… yet win_exists also does it for me

**Comment by JackUrb** [comment]
It seems any solution for running arbitrary script is going to encounter some kind of resistance from the browser, but I'm glad something is working for you.

Re some of these other features:

1. I haven't really investigated the use case for this (as it's more aesthetic over function), though if you feel it's worthwhile it isn't necessarily a hard change. You can implement it with the following. Extract some kind of "showDownloadButton" option from opts here: https://github.com/facebookresearch/visdom/blob/590c790562a938442c48e69a5f8dec821ae75fc4/py/server.py#L286 Use that option from the props of the pane to choose whether or not to display the download arrow. Once you expose the option into the pane in the above it will be forwarded for use in each of the panes' `props`, so you can update all of the pane files to only optionally show this:
https://github.com/facebookresearch/visdom/blob/590c790562a938442c48e69a5f8dec821ae75fc4/js/Pane.js#L77
2. I'm not sure what you mean by creating a window that creates other windows. If you want to remove that as well you can use the above procedure, but with a "showCloseButton" instead.
3. I'm soon going to be rolling out a feature that allows subscribing to browser events from within your visdom client, so instead of checking `win_exists` you should be able to subscribe a callback to the `env_cleared` event. Would that better cover your use case?

**Comment by OlegJakushkin** [comment]
Browser events sounds great!=)

"Window that creates other windows" like this (one with 4 buttons in the animation):
![ui101demo](https://user-images.githubusercontent.com/2915361/35871937-92fbddc8-0b76-11e8-86b8-7bc7a466eb00.gif)

**Comment by JackUrb** [comment]
Wow I didn't even know this kind of application of visdom was possible right now - it's impressive. Hopefully browser events can help you continue to flesh out this functionality 👍

Also do you think you might take a stab at adding the navbar functionality? If not feel free to open a new issue and I'll see when I have a short cycle to take care of it

**Comment by JackUrb** [comment]
@OlegJakushkin once https://github.com/facebookresearch/visdom/pull/260 is in you can start trying out the close callback rather than needing to use win_exists

**Comment by JackUrb** [comment]
Closing as we don't have a particular plan in mind to support script tags outside of frames

**Comment by paland3** [comment]
> Ended up using old-bad **`iframes`** (with flask, bootstrap and x3d inside), so it is a closed issue for me.
> 
Can you give an example how you embedded the script tag in an iframe?

**Comment by OlegJakushkin** [comment]
@paland3: Its just an html page with link to it in an iframe ‘src’. Any web site stand alone page, any approach can be used in them.

**Comment by mjstevens777** [comment]
Something that can make this even easier is the `srcdoc` attribute. That way you don't have to worry about any hosting as long as you have a [modern browser](https://caniuse.com/#search=srcdoc)
```python
import html
my_html = "<html>...</html>"
vis.text('<iframe srcdoc="{encoded_html}" style="{style}" />'.format(
    encoded_html=html.escape(my_html),
    style="width: 400px;height: 300px;"))
```
