### ISSUE TITLE
Missing dependencies when installing from pip on python2.7

### ISSUE THREAD

**Issue by jeandut** [facebookresearch/visdom#264]
I am runing visdom with Python2.7 and anaconda.
When I run python -m visdom.server I am missing a ton of dependencies all of them located in a subfolder of the visdom/static/ in site-packages
bootsrap.min.css
jquery.min.js
bootsrap.min.js
react-resizable-styles.css
layout_bin_packer etc.
I downloaded it using pip. Any idea why it is happening and where I could get those missing dependencies ?

**Comment by JackUrb** [comment]
These dependancies are supposed to be downloaded by the server when you launch, however they may not succeed if you're launching visdom through a proxy or on a VM without a network connection (or any other reason that may prevent those downloads). This issue is further documented near the start of our [contributing guidelines](https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md).

**Comment by jeandut** [comment]
Thanks for the quick answer I figured it was something like that. Looking into this asap.

**Comment by jeandut** [comment]
I just read the doc it is clear now. Closing the issue thank you again for the support.
