### ISSUE TITLE
Env delete button initially disabled when modal opened.

### ISSUE THREAD

**Issue by sonack** [facebookresearch/visdom#292]
![image](https://user-images.githubusercontent.com/12935189/37244530-69e5ba86-24c5-11e8-8020-6580164684b0.png)

**Comment by JackUrb** [comment]
Hi @sonack - it appears from my testing there's a bug that causes the delete button to be disabled initially upon opening the manage envs dropdown, however it should become enabled if you select a different option and then go back to the option you want to delete.

Otherwise, the delete button is disabled when you're disconnected from the server.

**Comment by sonack** [comment]
@JackUrb  Yes, it works, thanks very much

**Comment by JackUrb** [comment]
I'm going to re-open this for issue tracking, as while I have a workaround above I want to hold this open until I fix the root cause.
