### ISSUE TITLE
Feature Request: Custom Interactive Html buttons

### ISSUE THREAD

**Issue by koulanurag** [facebookresearch/visdom#295]
Hi,
I was wondering if there is a feature to embed custom Html-Buttons in visdom which could send some signal to the server. Some example of the button functionality could be to "Pause", "Stop", "Resume" the script. 
I see we can embed html in the interface. However; It looks to me as if that would be a static page; which I guess currently cannot send some signal back to the server.

Thanks,
Anurag Koul

**Comment by JackUrb** [comment]
Hi @koulanurag - thanks for your interest in visdom! 

This kind of functionality has been discussed since https://github.com/facebookresearch/visdom/issues/25, was added to our 'roadmap' early this year, and has recently been enabled in https://github.com/facebookresearch/visdom/pull/260, which displays setting up this functionality specifically for _keyboard_ events. I intend to expose a way to create a form that will report changes to internal elements, thus allowing sliders, dropdowns, buttons, etc. sometime in the coming month or two.

If you're so inclined, I'd be happy to accept a PR that will enable the feature as you're describing it with just buttons though! You can refer to how the callback events are broadcast for keyboard events: https://github.com/facebookresearch/visdom/blob/8a7116dd42422c3fa351188633ce22152180578d/js/main.js#L511 and how the visdom client picks up those events: https://github.com/facebookresearch/visdom/blob/8a7116dd42422c3fa351188633ce22152180578d/py/__init__.py#L265 and how you might be able to create a new interactive HTML pane like: https://github.com/facebookresearch/visdom/blob/8a7116dd42422c3fa351188633ce22152180578d/js/TextPane.js#L12

We have a working implementation of the keyboard feature in our demo: https://github.com/facebookresearch/visdom/blob/a1076fc9e928262007d015c9f053fb98e56aa632/example/demo.py#L37

**Comment by JackUrb** [comment]
Alternately in the meantime you can just attach your desired functions to a text pane with the keyboard events registered, and then control your flow from there 😄

**Comment by koulanurag** [comment]
Thanks for suggesting Key-Board events. It can rescue me for the time being :)

Regarding PR:  If I could find sufficient time; I would definitely give it a try!

Thanks,
Anurag
