### ISSUE TITLE
[Feature Request] Marker style for individual lines (including dashes)

### ISSUE THREAD

**Issue by lozino** [facebookresearch/visdom#376]
Hi!

Is there a way to plot different kinds of lines on the same plot?

For example, let's say I want to visualize the mean and the variance of different variables over time, and I would like to plot something like:

mean(x1)  --> blue continuous line
var(x1)      --> blue dashed line
mean(x2)  --> red continuous line
var(x2)      --> red dashed line

and so on...

Is there a simple way to do this?

Thank you!

**Comment by JackUrb** [comment]
Unfortunately this isn't possible in any easy way just yet, as the line dash/dot style would be set [here](https://github.com/facebookresearch/visdom/blob/31f76766c09c7f2d381a09d624b8910cb866cbd7/py/visdom/__init__.py#L972) according to the [plotly format](https://plot.ly/javascript/line-charts/#line-dash) and we haven't set that up. It would make sense to include this as part of enhancing the entire markersize concept (which I've wanted to do since #149).

You can however package your own line data following the plotly guide and send it using `_send` as described [here](https://github.com/facebookresearch/visdom#generic-plots) and shown in the demo [here](https://github.com/facebookresearch/visdom/blob/31f76766c09c7f2d381a09d624b8910cb866cbd7/example/demo.py#L416).

**Comment by lozino** [comment]
That works thanks! What if I wanted to append new data to the existing plot?

**Comment by JackUrb** [comment]
You should be able to use the same `_send` operator but with `endpoint='update'` and sending the same `update='append'` parameter that visdom does in `visdom.scatter`. Note that I've never tried this, but it should work in theory.

On Jun 13, 2018, at 4:12 AM, lozino <notifications@github.com<mailto:notifications@github.com>> wrote:


That works thanks! What if I wanted to append new data to the existing plot?

**Comment by JackUrb** [comment]
Ah yes to update using `endpoing='update'` you need to specify the name of the trace you are updating, as in the way that [scatter handles updates](https://github.com/facebookresearch/visdom/blob/31f76766c09c7f2d381a09d624b8910cb866cbd7/py/visdom/__init__.py#L1003). It needs this to know what specifically you're targeting

**Comment by lozino** [comment]
I have tried doing that with no positive result. Here's the snippet i am using for testing:

  ```
for i in range(10):
    trace = dict(x=[i], y=[i], mode="markers+lines", type='custom',
                 marker={'color': 'red', 'symbol': 104, 'size': "10"}, name='1st Trace')
    layout = dict(title="First Plot", xaxis={'title': 'x1'}, yaxis={'title': 'x2'})
    if i < 1:
        self.visualizer._send({'data': [trace], 'layout': layout, 'win': 'mywin', 'name': '1st Trace'})
    else:
        self.visualizer._send({'data': [trace], 'layout': layout, 'win': 'mywin', 'name': '1st Trace', 'append': True},
                              endpoint='update')
```

Again, whenever I add endpoint='update' it stops doing anything (it just plots the point (0, 0), and without it it replaces everything up to the point (9, 9)). Have I passed the name of the trace the wrong way? It would be very appreciated if you could point me in the right direction.

Thank you!

**Comment by JackUrb** [comment]
Turns out this won't work without the change in #377, but if you make those changes locally you'll be able to use exactly your testing snippet and have it work!

**Comment by dspoka** [comment]
@lozino I'm using the exact code you have in the snippet provided and I locally added the #377 changes but it seems to still only show the (0,0) point. Am I doing something else wrong?

**Comment by m45yang** [comment]
Hey @lozino, check out #523. Should be the feature you requested for!
