### ISSUE TITLE
Permission to create type stubs on typeshed

### ISSUE THREAD

**Issue by malmaud** [facebookresearch/visdom#388]
Hi,
I'll like to add a type annotation stub to the Python [typeshed](https://github.com/python/typeshed) for visdom for the benefit of people using a static type checker. I already have a draft of one written, but I need the permission of one of the visdom maintainers here to officially submit it.

**Comment by JackUrb** [comment]
Hi @malmaud - we're happy to give permission for typeshed stubs, however they will have to be compatible with [pyre](https://pyre-check.org/) typechecking as well as those required by typeshed's contributing guide (`mypy`, `pytype`, and `flake8`). 

As an aside, we'd actually be happier to put the typechecking directly into the visdom codebase, this way we can maintain it in one location. If you're willing to help towards that effort rather than using typeshed (which typeshed [actually prefers](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library)) I'd be happy to review a PR here.

**Comment by malmaud** [comment]
Oh ya, that would be great to put them in the codebase. I can submit a PR for that. 

Do you have a preference for the type annotations being inline with the rest of the codebase, or rather in separate stubs? I personally think the former is a bit neater since it gives code a self-documenting quality, but whatever works for you.

**Comment by JackUrb** [comment]
In-line is definitely preferred - I feel the same way

On Jun 19, 2018, at 12:44 PM, Jon Malmaud <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh ya, that would be great to put them in the codebase. I can submit a PR for that.

Do you have a preference for the type annotations being inline with the rest of the codebase, or rather in separate stubs? I personally think the former is a bit neater since it gives code a self-documenting quality, but whatever works for you.

**Comment by malmaud** [comment]
So as I delved into this, I realized a problem with in-line annotations occurs if you want to preserve Python 2.7 compatibility (which I assume you do). If so, you have to resort to the clunky syntax of giving all type information in the form of comments (https://mypy.readthedocs.io/en/latest/python2.html) and cannot use the nice Python 3 type annotation syntax. But if you use stubs, the stubs can use the nice annotation syntax while Python 2 users still get static type checking.

That pushes me in the direction of using stubs, but what do you think?

**Comment by JackUrb** [comment]
Agh so I guess inline is an impossibility for now (all the more reason I'd love it if people moved passed 2.7 😢). In that case if stubs end up having the better syntax overall then I'd feel it's a fair compromise between 2.7 support and optimal style.
