### ISSUE TITLE
training gets very slow when visualizing plots on visdom

### ISSUE THREAD

**Issue by ansabsheikh9** [facebookresearch/visdom#413]
Use this to open other questions or issues, and provide context here.
Hi,
I am using PyTorch to train my network and Visdom to visualize,
Each forward pass is taking almost .07 sec but when i start to visualize results on visdom, training gets very slow like 0.2 secs for each epoch, and also the visualization gets very heavy and slow to zoom in or out. Any Idea why it is happening.
Best Regards

**Comment by lvdmaaten** [comment]
Without additional context, it is hard to say anything meaningful. What are you trying to visualize, and why do you want to push a new visualization every 0.1 seconds? Where does your visdom server run and what is the interconnect with the client? Etc. etc. If, for instance, you're trying to make a scatter plot with 10 million points in it, this is completely expected behavior.

Please us this template to provide additional context: https://github.com/facebookresearch/visdom/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by flamz3d** [comment]
> Without additional context, it is hard to say anything meaningful. What are you trying to visualize, and why do you want to push a new visualization every 0.1 seconds? Where does your visdom server run and what is the interconnect with the client? Etc. etc. If, for instance, you're trying to make a scatter plot with 10 million points in it, this is completely expected behavior.
> 
> Please us this template to provide additional context: https://github.com/facebookresearch/visdom/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

We've been chasing down a huge performance bottleneck getting progressively worse as training goes on to this particular issue. To me this is showstopper in terms of adopting visdom. Of course one should not get a linear performance hit while training on the client (!) due to sending telemetry data to a server.
