### ISSUE TITLE
Visdom over Remote GPU Cluster

### ISSUE THREAD

**Issue by svj1991** [facebookresearch/visdom#417]
I have been looking around for some time to see if I could use Visdom over a remote GPU cluster. 
It might be possible already, I'm not sure as I could not find any help regarding this.
Essentially, we have multiple GPU servers in our cluster and the GPU assignment happens at run-time. So, I'm not sure how to use Visdom in such a setting or where to create a Visdom server. It would be great if someone could help with this.

Thanks.

**Comment by lvdmaaten** [comment]
The sole reason for creating visdom was because we wanted to be able to monitor lots of jobs running on a (GPU) cluster in a single dashboard.

You can run the visdom server on any server that you want, provided that your remote machines can connect to that server over http. In each of your jobs running remotely, you connect to that same server using the `server` and (optionally) `port` arguments of the `Visdom()` constructor, and all your plots will end up on the same visdom dashboard. Have each job use different window handles to make sure jobs don't overwrite each other's visualizations.

Why doesn't this workflow work for you?

**Comment by svj1991** [comment]
Thanks @lvdmaaten. I figured out how to use server, port and eids to set it up as required. I guess I was a little confused about how to use these properly. It has all the desired functionalities already. We can close this now I think.

Thanks, once again

**Comment by mhusseinsh** [comment]
@svj1991  Hello,
I am also connecting on a HPC with multiple GPUs. Can I know exactly what did you do to connect your visdom server ?

**Comment by 12cheny** [comment]
May you show the whole process, I can't open the web page in my own computer.
