### ISSUE TITLE
opts.yticklabels are ignored

### ISSUE THREAD

**Issue by dizcza** [facebookresearch/visdom#449]
**Bug Description**
Please enter a clear and concise description of what the bug is.
The docs say I can use `opt.xticklabels` and `opt.yticklabels` in some functions. I'd like to use them in heatmap.

**Reproduction Steps**
```
viz = visdom.Visdom()
X = np.random.rand(2, 4)
viz.heatmap(X, win='my_win', opts=dict(
    xtickslabels=['x0', 'x1', 'x2', 'x3'],
    yticklabels=['women', 'men'],
))
```

**Expected behavior**
Heatmap with specified x- and y-labels as strings.

**Got**
Heatmap with default integer-based x- and y-labels. Labels are ignored.

**Comment by JackUrb** [comment]
I'll take a look to see why Plot.ly isn't handling these labels properly for heatmaps

**Comment by JackUrb** [comment]
Alright finally getting to this, it's because as noted [in the docs](https://github.com/facebookresearch/visdom#visheatmap), heatmaps use special labels for this (`columnnames` and `rownames`) because plotly consumes them as data input rather than formatting input. You should still pass them through opts, but as:
```
viz = visdom.Visdom()
X = np.random.rand(2, 4)
viz.heatmap(X, win='my_win', opts=dict(
    columnnames=['x0', 'x1', 'x2', 'x3'],
    rownames=['women', 'men'],
))
```
