### ISSUE TITLE
Feature Request: `video()` support mp4/avi/gif outputs

### ISSUE THREAD

**Issue by zuoxingdong** [facebookresearch/visdom#46]
It could be convenient if the support for mp4/avi/gif format with 4D Tensor input is added

**Comment by lvdmaaten** [comment]
Doesn't this commit implement exactly that?

https://github.com/facebookresearch/visdom/commit/4b99344bd6ec648656bf057d018b578c986cfaf9

**Comment by zuoxingdong** [comment]
@lvdmaaten If I got it correctly, it can play mp4 file if the path is the input. It seems from the commit that if tensor to be passed, the `videofile` has fixed `.ogv` extension.

**Comment by lvdmaaten** [comment]
I initially tried exporting in MP4 format with the MJPG codec; the resulting videos played in Safari but not in Chrome: https://productforums.google.com/forum/#!topic/chrome/PslmTeeM8Fo

Using the Theora codec in OGG format was the only rendering I could get to work in Chrome (an option like WebM didn't work because ffmpeg wouldn't render it). The HTML5 codec situation is pretty messy in general: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility

If you have suggestions on more robust solutions, those are very welcome of course!

**Comment by j-min** [comment]
Is there a way to upload gif format?
I want to compare different gif files made by NN models with different hyperparameters.

**Comment by lvdmaaten** [comment]
There is no native GIF support at present, but you could read the GIF as a 4D numpy tensor, and pass that to the `video()` function:

```
from scipy import ndimage
imtensor = ndimage.imread('imagefile.gif')
viz.video(tensor=imtensor)
```

**Comment by j-min** [comment]
It seems 4D numpy tensor doesn't work properly with `video()`

```
# (392, 242, 3)
imtensor = ndimage.imread(gif_path)

# (3, 1, 392, 242)
imtensor = np.expand_dims(np.rollaxis(imtensor, 2), 1)

print(imtensor)

vis.video(tensor=imtensor)
```
When I run the code above at Mac OSX python 3.6, it creates a empty video window.
![image](https://user-images.githubusercontent.com/18069263/27552580-e5051174-5ae2-11e7-85fe-2af30521728b.png)

which contains
```
 <video controls>
                <source type="video/ogg" src="data:video/ogg;base64,">
                Your browser does not support the video tag.
            </video>
        
```


Below is the stderr.

```
(3, 1, 392, 242)
OpenCV: Frame size does not match video size.
OpenCV: Frame size does not match video size.
OpenCV: Frame size does not match video size.
2017-06-27 02:41:38.722 python[86168:13306283] WARNING: -finishWriting should not be called on the main thread.
```
Do you have any idea?

**Comment by JackUrb** [comment]
Closing as gif-through-4D-tensor support seems to be blocked by the bug in #209, and thus this is something of a duplicate issue.
