### ISSUE TITLE
[Feature Request] Dimension argument for video and images

### ISSUE THREAD

**Issue by tobyclh** [facebookresearch/visdom#466]
**Is your feature request related to a problem? Please describe.**
Video input requires LxHxWxC amd images grid takes BxCxHxW.
It doesn't seems right to me to have a different signatures for the two.

**Describe the solution you'd like**
I would personally prefer to change video input dimension to LxCxHxW instead.

**Describe alternatives you've considered**
Another way would be change image input to BxHxWxC, but I don't think that is feasible, given the nature of how images are produced etc.

**Comment by JackUrb** [comment]
Hi @tobyclh - I understand the discrepancy is somewhat strange but at this point it could be frustrating for existing users for me to change the standards. There's a better solution though in making it so that each of these take a dimensions argument string of the form `'LxHxWxC'` and then the input is properly transformed given the dimensions argument. If you're interested in implementing something like that I'd be happy to accept a PR. Otherwise I'll move to add it once I start working on my next batch of fixes.
