### ISSUE TITLE
Property panes will not try to reconnect after server failure

### ISSUE THREAD

**Issue by amitibo** [facebookresearch/visdom#497]
**Bug Description**
The *backchannel* socker of a python *client* (used to receive events from the UI) will not try to reconnect after a temporary *server* failure. This means that property panes will stop working (the python *clients* will not receive events from the *server*). This is in contrast to standard panes (e.g. plotly plots) that will continue after a temporary *server* failure.

The problem lies in the following line:
https://github.com/facebookresearch/visdom/blob/d7b30821ce87a02c7f98726ebe02e521574c0c5d/py/visdom/__init__.py#L425

**Reproduction Steps**
1. Start a *visdom* server.
2. Use the python API to open a property pane in the UI.
3. Shutdown and restart the *visdom* server.
4. Manipulating the properties in the property pane will have no effect in the *client* side (python API).

**Expected behavior**
The python client should try (at least periodically) to reconnect to the *server*, thus allow the property pane functionality to recover from server failures. For example, commenting the above line solves the issue.

**Comment by JackUrb** [comment]
Hi @amitibo - this is a good catch. That line existed to be able to disable the backchannel socket if the connection was refused on the initial setup/run, however I didn't realize it could be triggered during an intermittent server outage. 

The fix would be to only set that flag to false if connection was refused and visdom had never successfully acquired a back channel socket. I'd be happy to accept a PR with this fix! (Otherwise I'll tackle it next chance I have to go through the backlog)

**Comment by JackUrb** [comment]
Some corporate or otherwise private/secure networks have socket related ports closed in a way that it can be difficult to configure them properly, but visdom can still _work_ as a simple visualizer in those circumstances as the back channel is only required when users want scripts that can interact with the frontend directly (like properties panes)

**Comment by JackUrb** [comment]
Closing as you fixed this in #499. Thanks for the fix!
