### ISSUE TITLE
[Feature Request] Custom url paths to different visdom instances on same server

### ISSUE THREAD

**Issue by luzhilin19951120** [facebookresearch/visdom#511]
I suppose my situation to be a very common one, that many of us share one server on which we run pytorch for experiments.

So do Visdom support this kind of multi-user scene? Up till now, when I start a Visdom server, anyone else on the public server can see it. And the env created by different user mix together, which cause trouble in finding the specific one we need.

The port is quite limited and let's assume we can only use 8097

**Comment by JackUrb** [comment]
For the most part we've solved this issue by using different ports. It would be possible to add functionality in `server.py` that sets tornado running on a base path `url_path` which would default to `''`, but could be set to something unique. Then you'd need to also make the `Visdom.visdom` object accept a `url_path` parameter so that it can try connecting to `<hostname>:<port>/<url_path>`. I'd be happy to accept the PR with these changes if you implement them.

**Comment by luzhilin19951120** [comment]
That is perfect solution. However, it hasn't been pushed to pipe package yet and the github version is not steady enough~

**Comment by luzhilin19951120** [comment]
For instance, I reported some problems that I occurred in issue #512

**Comment by JackUrb** [comment]
The above solution hasn't been coded, I was saying you could add it yourself if you wanted to. The problems noted in #512 are discrepancies between the pip version and the version you get from installing from source.

**Comment by JackUrb** [comment]
Correcting my earlier statement - this has actually already been implemented in #471. I'll be updating the PyPI version sometime soon, but otherwise if you need to use this feature you'll have to install from source.
