### ISSUE TITLE
Multiple traces with only one X point

### ISSUE THREAD

**Issue by tom-programming** [facebookresearch/visdom#539]
Using the `vis.line` function:

    vis.line(X=np.array((1,2)), Y=np.array(((1,2),(3,4)))) # works
    vis.line(X=np.array((1,)), Y=np.array(((1,),(3,)))) # does not work

How can I plot multiple traces in one windows when I have only one X point? I intend to plot the two traces by updating the windows for every new X point but I cannot start

**Comment by JackUrb** [comment]
The issue here is this particular line: https://github.com/facebookresearch/visdom/blob/530e786b9a8005bfbac24092cd52ea6d0f4e3a81/py/visdom/__init__.py#L1339
Unfortunately I can't fully parse what the purpose of this block is (I suspect it has to do with plotting just using Y values, but it was written before my time without comment) and I'm not confident I can remove it. @lvdmaaten do you know why this reshape exists?

As far as solving your problem for now, you should be able to append a new trace after making the original point by name as such:
```
win = vis.line(X=np.array((1,)), Y=np.array(((1,))))
vis.line(X=np.array((1,)), Y=np.array(((3,))), win=win, update="append", name="2")
```
Unfortunately if you'd like to continue adding points one at a time, you'll have do do so by referring to the traces by name as such:
```
vis.line(X=np.array((2,)), Y=np.array(((3,))), win=win, update="append", name="1")
vis.line(X=np.array((2,)), Y=np.array(((5,))), win=win, update="append", name="2")
```
