### ISSUE TITLE
question: how to export the plot into Plot.ly

### ISSUE THREAD

**Issue by ebagdasa** [facebookresearch/visdom#556]
I am curious, there used to be a save button that would redirect me to Plot.ly to edit the graph, I can't find it anymore in the current version I use (0.1.8.8)

**Comment by JackUrb** [comment]
Hi @ebagdasa - sorry something must've happened to the old save button, but there still is one. Unfortunately its the `>>` link that is obscured by the pane resizing anchor. For now you can hide that element, but the real fix is going to be to find a way to either move that up or add a margin to the bottom of the container within the PlotPane. We'll take a look

**Comment by ebagdasa** [comment]
haha, got it. Steps for others:
I had to delete a span (pane resizing anchor) that overlayed `>>` by using Developer tools in Chrome. Just right click on the `>>` and select inspect, it should open a console with exact location in html:
```
<span class="react-resizable-handle" style="touch-action: none;"></span>
```
Press `delete` and you should be able to click on `>>`.

**Comment by pringshia** [comment]
IMO the quickest fix here with the least code churn would be to just update the label text to be slightly larger so that it it's hit zone isn't completely eclipsed by the pane resizing anchor.

For example:

![screen shot 2019-02-12 at 4 56 00 pm](https://user-images.githubusercontent.com/425059/52670662-1cfa4e80-2ee7-11e9-9a48-29f95ba41281.png)

This would just involve updating the `linkText` in the following line:

https://github.com/facebookresearch/visdom/blob/bdbed59a2ec469ae61d74d4c94c50d5ae0e8629d/js/PlotPane.js#L71

**Comment by zhangchenkai** [comment]
Why not move it to somewhere else? 
The latest version still need to delete the element manually.

**Comment by pringshia** [comment]
@zhangchenkai That's because this was never merged in, it fell off my radar - will get it fixed and merged in shortly!
