### ISSUE TITLE
How far back is pip to current releases, and why? 

### ISSUE THREAD

**Issue by BramVanroy** [facebookresearch/visdom#571]
The read-me explicitly states, when using pip 'STABLE VERSION, NOT ALL CURRENT FEATURES ARE SUPPORTED'. What does this mean in practice?

I'm also interested in the reason why the pip 'branch' is behind like this. Is the release schedule on pip so slow?

**Comment by JackUrb** [comment]
As for the what it means and when, the most recent bump is in #551, everything following that hasn't been put on pip yet. In general you can trace the most recent version on pip by looking at the last time the VERSION file has changed.

For the why, due to the fact that the entirety of work on visdom at the moment comes from either external contributors (who are incredibly appreciated) or spare cycles from a few engineers working on other projects, we don't have a fast enough development cycle to ensure that features have been fully tested and proven as better functioning. (We're looking to have more dedicated visdom support in the near future though!) We also haven't had the bandwidth to introduce automated testing to the visdom codebase yet, so most of that is done manually and via dogfooding the most recent version available from source. While I try my best to be prompt in responding to issues, I generally don't push a new version to pip unless I am sure I have the bandwidth to spare for a potential influx of new issues about how something broke in the new version.

**Comment by BramVanroy** [comment]
Very nice to get some inside into the development of Visdom. I always assumed that there was a separate branch at Facebook working on machine learning things, with squads for e.g. (py)torch and visdom. It's a pity that you don't have the time and resources to make this even better because there is a growing interest in PyTorch and visdom works well with it. Nevertheless, thank you for all your time and effort!

**Comment by JackUrb** [comment]
"PyTorch and visdom works well with it" - this is the very reason we're looking to invest more into visdom in this half and into the future. Embeddings, graph visualizations, and improved save/load interfaces are first up on the list. Anyways - thanks for your interest!
