### ISSUE TITLE
Client crashes if server stops responding

### ISSUE THREAD

**Issue by Nintorac** [facebookresearch/visdom#576]
**Bug Description**
When running an experiment if the server crashes it takes the experiment down with it.

**Reproduction Steps**
Enter steps to reproduce the behavior:
1. Run many experiments
2. Cause server overload
3.Time out occurs on the training instance and the experiment fails

**Expected behavior**
The client is not dependent on the server being up, plots fail silently or with a warning.

**Additional context**
Unfortunately the experiments I had running were in a notebook that had been closed so I was not able to get the log outputs. 

The visdom server had been running for a while and had many plots which I think contributed to the server failure

**Comment by JackUrb** [comment]
At the moment plotting failures should have followed the expected behavior as everything is gated between a try that suppresses errors: 
https://github.com/facebookresearch/visdom/blob/9a5698ef3230ce008a4a7bd4a3442094dadf1f19/py/visdom/__init__.py#L545
But going without the logs, my first guess is that the timeout doesn't actually fall under the `requests.RequestException` caught here:
https://github.com/facebookresearch/visdom/blob/9a5698ef3230ce008a4a7bd4a3442094dadf1f19/py/visdom/__init__.py#L560
Which is apparently the case according to the [requests documentation](http://docs.python-requests.org/en/master/api/#exceptions). The simple fix is to catch all of the exception types we expect. I'll be taking a pass to fix a number of visdom bugs that have been on the backlog mid next week, so I'll handle this then if nobody else gets to it. Thanks for flagging @Nintorac.
