### ISSUE TITLE
how to set xlim and ylim?

### ISSUE THREAD

**Issue by xin-w8023** [facebookresearch/visdom#577]
Use this to open other questions or issues, and provide context here.

**Comment by JackUrb** [comment]
Assuming you're trying to set x and y bounds for your plots (as you've provided no additional details), the answer is to provide _both_ `xtickmin` and `xtickmax` for the x bounds and `ytickmin` and `ytickmax` for the y bounds, as in the example: https://github.com/facebookresearch/visdom/blob/9a5698ef3230ce008a4a7bd4a3442094dadf1f19/example/demo.py#L145
Providing just one or the other will not work as Plot.ly requires a range from start to end in order to set custom bounds.

**Comment by xin-w8023** [comment]
sorry that i did not describe my question clearly, but you got me. thanks

**Comment by JackUrb** [comment]
No worries - It just makes it easier for others to also learn with details. Feel free to ask anything if you run into any future issues with visdom!
