### ISSUE TITLE
KeyPress Callbacks for Plot windows and adding meta data to window?

### ISSUE THREAD

**Issue by Nzteb** [facebookresearch/visdom#661]
Hi, I'm happy to split in two windows and/or create a feature request instead.

1. Is there a built in possibility to add _external_ meta information to a window? At the moment, I am adding meta information (e. g. to a line plot)  by:
vis.line(X=[None],Y=[None], opts={Metadic:{"metakey1":metaval1})
This works just fine but is there a better way compared to the "abuse" of opts?

2. Are the KeyPress callbacks on a plot window not supported at the moment? I was not able to get this running, but the documentation is not specific about this.

Background: I want to access the meta data from 1. easily from the browser. At the moment, I'm using a property window where I enter the window name and then use the callbacks there. I'd love to have a callback on a plot window such that the user e. g. only has to type "M" and the meta data appears (e. g. could be a new text window).

**Comment by JackUrb** [comment]
Hi @Nzteb - the callbacks/events functionality is something we're looking to expand, but haven't had too much time to dedicate to a good and extensible design. The above functionality you're interested in - metadata for windows for the purpose of event management - is one such thing I've been considering how to best implement, but as of yet the above is really the only way to manage it.

As far as KeyPress callbacks on plots, they aren't yet supported simply because nobody has tried to put them there yet. Some guidance for how they'd be implemented in [PlotPanes](https://github.com/facebookresearch/visdom/blob/d2a5eecf337d9fd2f633b5c2772ca0c2e16e9755/js/PlotPane.js#L13) can be seen in [ImagePanes](https://github.com/facebookresearch/visdom/blob/d2a5eecf337d9fd2f633b5c2772ca0c2e16e9755/js/ImagePane.js#L51). We'd definitely welcome a PR that implemented it for plots as well.

**Comment by Nzteb** [comment]
Awesome, I see. Thanks for the answer and your great work!
