### ISSUE TITLE
how to visualize feature map?

### ISSUE THREAD

**Issue by cjnewstar111** [facebookresearch/visdom#662]
Use this to open other questions or issues, and provide context here.
the viz.image and viz.images only support the channel with 3. but the channel in feature maps alwarys > 3.  for example,  n=1, c=32, h=128, w=128. then how to visualize this feature maps? thanks.

**Comment by JackUrb** [comment]
Hi @cjnewstar111 - there's no real agreed upon proper visualization for many channel feature maps like the one you're describing using images. I'd encourage you to look at some tutorials for visualizing feature maps elsewhere (such as [this one](https://machinelearningmastery.com/how-to-visualize-filters-and-feature-maps-in-convolutional-neural-networks/)) so that you can properly pre-process your features, and then you can plot the resultant images using the `images` pane.

**Comment by linnae544** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jack Urbanek <notifications@github.com> Date: 8/22/19  1:05 PM  (GMT-06:00) To: facebookresearch/visdom <visdom@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [facebookresearch/visdom] how to visualize feature map? (#662) Hi @cjnewstar111 - there's no real agreed upon proper visualization for many channel feature maps like the one you're describing using images. I'd encourage you to look at some tutorials for visualizing feature maps elsewhere (such as this one) so that you can properly pre-process your features, and then you can plot the resultant images using the images pane.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/facebookresearch/visdom/issues/662?email_source=notifications\u0026email_token=AM36SSGB3ZB5OWOBFDKJKMDQF3IPBA5CNFSM4IOQIYFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD455JSI#issuecomment-524014793",
"url": "https://github.com/facebookresearch/visdom/issues/662?email_source=notifications\u0026email_token=AM36SSGB3ZB5OWOBFDKJKMDQF3IPBA5CNFSM4IOQIYFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD455JSI#issuecomment-524014793",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
