### ISSUE TITLE
update=append with initialization as (0, 0) 

### ISSUE THREAD

**Issue by tadpole** [facebookresearch/visdom#690]
When I plot the accuracy curve by update=append. It is very ugly that the curve starts with (0, 0). How can I fix it?

Init:
`viz.line([0.], [0.], win='accuracy', opts=dict(title='acc'))`
Update:
`viz.line([acc], [iter], win='accuracy', update='append')`

**Comment by JackUrb** [comment]
Hi @tadpole - the curve starts at (0,0) because you're initializing it as such. If you are intending to use the same `win` however, you don't actually need the first init call, and can just use:
`viz.line([acc], [iter], win='accuracy', update='append', opts=dict(title='acc'))`
Visdom will automatically init on an `append` call if no such window already exists.

**Comment by tadpole** [comment]
Thanks. But when I run the code twice in that way, there will be two curves in the windows.

**Comment by JackUrb** [comment]
You can check `win_exists('accuracy')` for your window, and delete the window with `close('accuracy')` if it does to prevent this.
