### ISSUE TITLE
Is Visdom development dead?

### ISSUE THREAD

**Issue by jramapuram** [facebookresearch/visdom#751]
I see a few PRs being merged from ~2 mo ago, but no active development, eg: https://github.com/facebookresearch/visdom/pull/675 has been in progress since last year.

I get it that we all have time constraints and things to focus on (I'm a prime example of this with my ~4yr old cross-GPU ML lib 😂). Just want to know if I should start refactoring my code to move to an alternative like wandb or not.

**Comment by JackUrb** [comment]
Hi @jramapuram - I've mostly been caught up in other projects and following survey feedback on visdom there wasn't enough immediate interest for me to motivate others to help out on the work. I hope to return someday as I think it's still ideal for visualizing experiments under custom workflows, but until the requirements of my projects bring me back to using visdom I likely won't have much bandwidth to work on improvements.

**Comment by ivanov-v-v** [comment]
Hi @JackUrb! Actually, Visdom is invaluable to my work as ML engineer and researcher, and this is probably true for many others as well. We would greatly appreciate it if you could invest more time into this project (at least, do more PR reviews). This could change ML experience for better for many developers all over the world, because it is much more functional than TensorBoard which everyone is using. ;) Would be happy to participate as well!

**Comment by ivanov-v-v** [comment]
You could also consider submitting Visdom to GSOC, this can help to push the project forward and make it more recognisable in the community as well

**Comment by jramapuram** [comment]
@JackUrb : thanks for the update. Just to clarify again, Visdom and your work on this project is **awesome** and greatly appreciated. I totally understand being strewn between projects. Best of luck.

**Comment by JackUrb** [comment]
Closing, as is answered in #753.
